version: "3.8"

services:
  mysqldb:
    platform: linux/arm64
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${LOCAL_PORT}:${DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQLDB_PASSWORD"]
      interval: 20s
      timeout: 5s
      retries: 10
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: template
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "${USERNAME}",
        "spring.datasource.password" : "${PASSWORD}",
        "spring.datasource.initialization-mode": "always",
        "jwt.expiration" : "${JWT_EXPIRATION}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
