version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  mysqldb:
    platform: linux/arm64
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$DATABASE_PASSWORD"]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  auth-service:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    build: ./backend/auth-service
    env_file: ./.env
    expose:
      - 8080
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - app-network

  user-service:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    build: ./backend/user-service
    env_file: ./.env
    expose:
      - 8080
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - auth-service
      - user-service
    volumes:
      - ./html5up-stellar/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

