name: Service CI

on:
  push:
    branches:
      - 'service/*'  
  pull_request:
    branches:
      - 'main'  
      - 'service/*'
      

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }} 
          MYSQL_DATABASE: ci-database
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set environment variables
      run: |
        echo "DATABASE_NAME=ci-database" >> $GITHUB_ENV
        echo "DATABASE_USERNAME=${{ secrets.MYSQL_USERNAME }}" >> $GITHUB_ENV
        echo "DATABASE_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
        echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
        echo "DATABASE_PORT=3306" >> $GITHUB_ENV
        echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> $GITHUB_ENV
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h 127.0.0.1 -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e 'select 1'; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Build with Maven
      run: | 
        if [[ -n "${GITHUB_HEAD_REF}" ]]; then
            cd backend/${GITHUB_HEAD_REF##*/}
        else
          cd backend/${GITHUB_REF##*/}
        fi
        mvn clean verify

    - name: Run tests with Maven
      run: |
        if [[ -n "${GITHUB_HEAD_REF}" ]]; then
            cd backend/${GITHUB_HEAD_REF##*/}
        else
          cd backend/${GITHUB_REF##*/}
        fi
        mvn test
